package application

import (
	_ "github.com/dindasigma/go-docker-boilerplate/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/dindasigma/go-docker-boilerplate/packages/api/controllers"
	"github.com/dindasigma/go-docker-boilerplate/packages/api/middlewares"
	httpSwagger "github.com/swaggo/http-swagger"
)

func initializeRoutes() {
	// Home Route
	router.HandleFunc("/", middlewares.SetJSON(controllers.HomeController.Home)).Methods("GET")

	// Login Route
	router.HandleFunc("/login", middlewares.SetJSON(controllers.LoginController.Login)).Methods("POST")

	// Users routes
	router.HandleFunc("/users", middlewares.SetTimeout(middlewares.SetJSON(controllers.UserController.Get))).Methods("GET")
	router.HandleFunc("/users/{id}", middlewares.SetJSON(controllers.UserController.GetByID)).Methods("GET")
	router.HandleFunc("/users", middlewares.SetJSON(controllers.UserController.Create)).Methods("POST")
	router.HandleFunc("/users/{id}", middlewares.SetJSON(middlewares.SetAuthentication(controllers.UserController.Update))).Methods("PUT")
	router.HandleFunc("/users/{id}", middlewares.SetAuthentication(controllers.UserController.Delete)).Methods("DELETE")

	// Swagger
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
}
